---
- name: Make sure project dir exists
  ansible.builtin.file:
    path: "{{ docker_compose_project_dir }}"
    state: directory
    mode: "0755"

- name: Copy docker-compose file
  ansible.builtin.template:
    src: "{{ docker_compose_template_file }}"
    dest: "{{ docker_compose_file_path }}"
    mode: "0744"
  notify: Docker Compose Up
