- name: Ensure dependencies packages are installed
  ansible.builtin.apt:
    name: gpg
    update_cache: true

- name: Install Docker keyring
  ansible.builtin.get_url:
    url: "{{ docker_apt_key_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
    force: false

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo }}"
    filename: docker.list

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
