---
- name: Run traefik docker compose
  ansible.builtin.include_role:
    name: docker_compose
  vars:
    docker_compose_template_file: "{{ docker_traefik_template_file }}"
    docker_compose_project_dir: "{{ docker_traefik_project_dir }}"

- name: Copy traefik config
  ansible.builtin.template:
    src: "traefik.yml.j2"
    dest: "{{ docker_traefik_project_dir }}/traefik.yml"
    mode: '0664'
